# encoding: UTF-8
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/gempackagetask'

Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'ActiveImap'
  rdoc.options << '--line-numbers' << '--inline-source'
  rdoc.rdoc_files.include('README.rdoc')
  rdoc.rdoc_files.include('doc/**/*.rdoc', 'lib/**/*.rb')
  rdoc.rdoc_files.exclude('lib/generators/**/templates/**/*.rb')
end

begin
  require 'rspec'
  require 'rspec/core/rake_task'

  Rspec::Core::RakeTask.new(:spec)
  
  namespace :spec do
    desc "Run specs to generate coverage"
    Rspec::Core::RakeTask.new(:rcov) do |spec|
      spec.rcov = true
      spec.rcov_opts = %[--exclude "core,expectations,gems/*,spec/resources,spec/spec,spec/spec_helper.rb,/Library/Ruby/*,config/*" --text-summary  --sort coverage]
    end
  end
rescue
  task :spec do
    abort 'Spec is not available. In order to run cucumber, you must: sudo gem install rspec'
  end
end

spec = Gem::Specification.new do |s|
  s.name = "activeimap"
  s.summary = %Q{An ActiveModel based IMAP Accessor }
  s.description = %Q{An ActiveModel based IMAP Accessor }
  s.email = 'info@spom.net'
  s.homepage = 'http://spom.net/'
  s.authors = ['Sven G. Broenstrup']
  s.files = Dir["{lib}/**/*", "VERSION", "README*", "LICENCE"]
  s.version = ::File.read(::File.join(::File.dirname(__FILE__), "VERSION")).strip
  s.add_dependency 'activesupport', '>= 3.0.0.beta3'
  s.add_dependency 'activemodel', '>= 3.0.0.beta3'
  s.add_dependency 'mail', '>= 2.2.0'
end

Rake::GemPackageTask.new(spec) do |pkg|
end

desc "Create a stand-alone gemspec"
task :gemspec  do
  open("#{spec.name}.gemspec", "w") do |f| 
    f.puts "# Generated by rake\n# DO NOT EDIT THIS FILE DIRECTLY\n"
    f.puts spec.to_ruby 
  end
end

task :gem => [:gemspec]
